#!/usr/bin/env bash
#
# PLAN-EQUIVALENCE-VERIFICATION-review.sh — run one Codex review round on
# the equivalence verification plan at plans/PLAN-EQUIVALENCE-VERIFICATION.md
#
# Usage:
#   ./PLAN-EQUIVALENCE-VERIFICATION-review.sh <Round>
# Example:
#   ./PLAN-EQUIVALENCE-VERIFICATION-review.sh 1
#
# Output:
#   ./PLAN-EQUIVALENCE-VERIFICATION-r{Round}-{YYYYMMDD}.md  (codex stdout)

set -euo pipefail

ROUND="${1:?Usage: $0 <Round>}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REVIEWS_DIR="$REPO_ROOT/codex-crypto-reviews"
DATE="$(date +%Y%m%d)"
OUT="$REVIEWS_DIR/PLAN-EQUIVALENCE-VERIFICATION-r${ROUND}-${DATE}.md"

PLAN_PATH="plans/PLAN-EQUIVALENCE-VERIFICATION.md"

PROMPT=$(cat <<PROMPT_EOF
You are reviewing a DESIGN PLAN (not source code) for "Turnkey C# SDK ↔
公式実装 同等性検証プラン" at:

  ${PLAN_PATH}

This is REVIEW ROUND ${ROUND}. The intent of the plan is to provide a
machine-verifiable equivalence-test strategy between this private C# SDK
(KyuzanInc.Turnkey.Sdk) and the upstream Turnkey TypeScript / Go / Rust
SDKs, on top of the already-merged 3-round Codex code reviews living in
codex-crypto-reviews/.

REQUIRED OUTPUTS (sections A-G must all appear in your output):

A. Plan provenance acknowledgement:
   - Plan file path (re-state verbatim).
   - Plan version (parse the "Status:" line and any "v# changes vs v(#-1)"
     table).
   - List the existing internal references the plan cites (codex-crypto-reviews/
     files, tests/Fixtures/ subtree, etc.) and confirm each cited file
     actually exists at the cited path. Flag any broken link.

B. Internal-consistency audit. For each numbered section (1-13) in the plan:
   - Does it conflict with claims made in another section?
   - Does it conflict with the existing
     codex-crypto-reviews/FINAL-INTEGRATED-REVIEW-20260523.md, with the
     existing tests/Fixtures/README.md provenance scheme, or with
     ApiKeyStamper.cs-codex-findings-reconciliation.md / Http.cs-codex-findings-reconciliation.md?
   - If yes: cite both sides (file:line ranges) and propose a one-line fix.

C. Cryptographic-claim audit. Verify each cryptographic / wire-format
   factual claim in the plan against the upstream pinned snapshots under
   codex-crypto-reviews/upstream-snapshots/. Specifically:
   - Plan claims Turnkey HPKE is NOT RFC 9180 and follows
     tkhq/qos/src/qos_p256/SPEC.md. Does the actually-pinned
     @turnkey/crypto@2.8.8 source under
     codex-crypto-reviews/upstream-snapshots/turnkey-crypto-2.8.8/ts-source/
     match that claim, or is the C# port talking to a different scheme?
   - Plan claims @noble/curves v1.3.0 purejs path emits low-S RFC 6979
     deterministic-k signatures. Is that load-bearing for the proposed
     Tier-2 Node-generated byte fixtures?
   - Plan claims @turnkey/api-key-stamper@0.5.0 produces JSON keys in
     order { publicKey, scheme, signature } and SIGNATURE_SCHEME_TK_API_P256.
     Confirm against pinned source.
   - Plan claims the published npm tarballs do NOT include test/fixture
     files. Confirm by listing the pinned tarball contents.
   For each claim: cite upstream-snapshots/...:line and either confirm or
   propose a correction.

D. Coverage / scope audit:
   - The plan promises a "MISSING-row-zero" coverage matrix between upstream
     __tests__/*.ts test() blocks and C# [Fact]/[Theory] methods. Walk
     the upstream test files in upstream-snapshots/*/ts-source/__tests__/
     and identify any upstream test() name that the plan's PR-3 would have
     to add to the C# side (call these out by name). This is to surface the
     actual scale of PR-3 before approval.
   - The plan proposes Tier-3 primitive standard vectors. List any
     Turnkey-used primitive the plan forgot (e.g., does the SDK use
     SHA-512 anywhere? Ed25519 for SOLANA export — should Ed25519 NIST
     vectors be added?).
   - The plan defers proof.ts implementation to a separate plan but
     proposes PR-11 to seed tests/Fixtures/proofs/. Is the fixture-only
     seeding harmful (e.g., committed JSON with no consumer)?

E. Operational risk audit:
   - The plan introduces a Node toolchain dependency in tests/Fixtures/Generators/.
     Walk the .github/workflows/*.yml under the repo to identify whether
     a Node setup step needs to be added to any existing CI workflow that
     might inadvertently exercise the Generators path.
   - The plan proposes monthly upstream-drift detection. Is the auto-issue-
     creation behavior bounded (no infinite issue creation if a drift
     persists for months)?
   - The plan claims fixture regeneration is platform-agnostic. Is there
     anything in @turnkey/crypto@2.8.8 or @noble/curves that is in fact
     platform-dependent (native modules, WASM)?

F. Plan-writing-quality audit:
   - Are all the listed PRs (PR-1 ... PR-14) actually independently
     mergeable, or do any of them depend on something the dependency
     column omits?
   - Are the listed "must-have Goals" each individually measurable, or
     are any of them vague (cannot be marked done objectively)?
   - Are any sections substantially redundant (Tier table appearing
     twice, FAQ repeating section bodies)?

G. Unresolved assumptions you could not verify in this round. Cite the
   plan line range where each assumption is made.

PASS criterion for this round: A is acknowledged; B has zero rows;
C has zero corrections proposed; D's PR-3 scope is bounded with a
concrete list (this is non-empty but the list IS the deliverable);
E has zero unbounded risks; F has zero blocking issues; G has zero
unverifiable assumptions.

DO NOT use phrases like "looks good" or "no issues found" without
producing sections A-F.
PROMPT_EOF
)

cd "$REPO_ROOT"
{
  echo "# Codex plan review — ${PLAN_PATH} — round ${ROUND} — ${DATE}"
  echo ""
  echo "Plan SHA: \`$(git log -n1 --format=%H -- "${PLAN_PATH}" 2>/dev/null || echo 'uncommitted')\`"
  echo ""
  echo "---"
  echo ""
  printf '%s\n' "$PROMPT" | codex exec \
    -s read-only \
    --skip-git-repo-check \
    -C "$REPO_ROOT" \
    -c model_reasoning_effort=high \
    - 2>&1
} > "$OUT"

echo "Wrote $OUT"
